---
name: Wheels

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 4 15 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}


jobs:
  wheels:
    name: Building for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-22.04-arm
          - os: windows-2022
          - os: windows-11-arm
          - os: macOS-14
          - os: ubuntu-24.04-riscv

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: "false"

      # Use the GitHub Action for all platforms except riscv64
      - name: Build wheels on ${{ matrix.os }}
        uses: pypa/cibuildwheel@ee02a1537ce3071a004a6b08c41e72f0fdc42d9a # v3.4.0
        if: ${{ !endsWith(matrix.os, 'riscv') }}
        env:
          CIBW_ARCHS: auto

      - name: Build wheels on ${{ matrix.os }}
        run: uvx --python 3.14 cibuildwheel --output-dir wheelhouse
        if: ${{ endsWith(matrix.os, 'riscv') }}
        env:
          CIBW_ARCHS: riscv64

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
...
